table GICS_MATRIX_2
	lineageTag: 4f3aff46-f842-40e1-9886-7c195b83fc68

	column GICS_SECTOR_CODE
		dataType: double
		lineageTag: a2d52bd2-ed5b-424c-911d-21d2c019b1e3
		summarizeBy: sum
		sourceColumn: GICS_SECTOR_CODE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'GICS Sector'
		dataType: string
		lineageTag: 1f8789a7-5dcb-4142-8fd6-61d12f4ec295
		summarizeBy: none
		sourceColumn: GICS Sector

		annotation SummarizationSetBy = Automatic

	column GICS_INDUSTRY_GROUP_CODE
		dataType: double
		lineageTag: 56375120-b57d-4a23-a122-065873cf169d
		summarizeBy: sum
		sourceColumn: GICS_INDUSTRY_GROUP_CODE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'GICS Industry Group'
		dataType: string
		lineageTag: 2917a430-f1d0-4203-88f2-49cfb707db8b
		summarizeBy: none
		sourceColumn: GICS Industry Group

		annotation SummarizationSetBy = Automatic

	column GICS_INDUSTRY_CODE
		dataType: double
		lineageTag: 67abf570-27e0-491d-aa95-58cd31298e30
		summarizeBy: sum
		sourceColumn: GICS_INDUSTRY_CODE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'GICS Industry'
		dataType: string
		lineageTag: 4507ecca-ee26-4f72-b00f-af0c9bb10aa0
		summarizeBy: none
		sourceColumn: GICS Industry

		annotation SummarizationSetBy = Automatic

	column TC_GICS_INDUSTRY_CODE
		dataType: double
		lineageTag: bf9e212e-8c8d-495a-b55c-a9464f772f4f
		summarizeBy: sum
		sourceColumn: TC_GICS_INDUSTRY_CODE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition GICS_MATRIX_2 = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(snowflake_url,"ANALYST_WH_XS"),
				    HUB_Database = Source{[Name="HUB",Kind="Database"]}[Data],
				    ASSET_Schema = HUB_Database{[Name="ASSET",Kind="Schema"]}[Data],
				    GICS_MATRIX_Table = ASSET_Schema{[Name="GICS_MATRIX",Kind="Table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(GICS_MATRIX_Table,{{"GICS_INDUSTRY_GROUP_NAME", "GICS Industry Group"}, {"GICS_INDUSTRY_NAME", "GICS Industry"}, {"GICS_SECTOR_NAME", "GICS Sector"}, {"GICS_SUB_INDUSTRY_NAME", "GICS Sub Industry"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"GICS Sub Industry", "GICS_SUB_INDUSTRY_CODE"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns", {"GICS Industry"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

