table HOLDING_2
	lineageTag: 8cb9b918-9bcd-4ace-b7bd-ae9681a3d32f

	column 'Period End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e6f280a1-ba27-4cd8-8146-1788ac9d705f
		summarizeBy: none
		sourceColumn: Period End Date

		variation Variation
			isDefault
			relationship: 2254aa8b-af45-4f09-84df-6aff37b56f2f
			defaultHierarchy: LocalDateTable_61f7f51e-d9ca-4a92-8517-88a3a5847959.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SOURCE_SYSTEM_CODE
		dataType: string
		lineageTag: 4471e830-48ce-4598-a45b-8204d61e8d9f
		summarizeBy: none
		sourceColumn: SOURCE_SYSTEM_CODE

		annotation SummarizationSetBy = Automatic

	column SOURCE_SYSTEM_SHORT_NAME
		dataType: string
		lineageTag: f278e7d1-15bf-463f-87ec-2c87af48128b
		summarizeBy: none
		sourceColumn: SOURCE_SYSTEM_SHORT_NAME

		annotation SummarizationSetBy = Automatic

	column SOURCE_SYSTEM_NAME
		dataType: string
		lineageTag: 13ba7a20-4644-4bc0-a24d-c90d71984767
		summarizeBy: none
		sourceColumn: SOURCE_SYSTEM_NAME

		annotation SummarizationSetBy = Automatic

	column PORTFOLIO_IDENTIFIER
		dataType: string
		lineageTag: c1b87c87-f0c7-452a-a0df-ff5e2edc6667
		summarizeBy: none
		sourceColumn: PORTFOLIO_IDENTIFIER

		annotation SummarizationSetBy = Automatic

	column 'Instrument Identifier'
		dataType: string
		lineageTag: 54fc4149-d563-4d8f-988f-2985bf878d99
		summarizeBy: none
		sourceColumn: Instrument Identifier

		annotation SummarizationSetBy = Automatic

	column CUSTODIAN_ACCOUNT_IDENTIFIER
		dataType: string
		lineageTag: 4480a0af-0588-4dd4-b2c1-0ac2748e402e
		summarizeBy: none
		sourceColumn: CUSTODIAN_ACCOUNT_IDENTIFIER

		annotation SummarizationSetBy = Automatic

	column 'Position Quantity'
		dataType: double
		lineageTag: 0062d750-3169-455a-b55a-aa001313fc9b
		summarizeBy: sum
		sourceColumn: Position Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ORIGINAL_FACE_AMOUNT
		dataType: double
		lineageTag: 96989fb4-bb67-4ab2-8a0c-87cf990285de
		summarizeBy: sum
		sourceColumn: ORIGINAL_FACE_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CURRENT_FACE_AMOUNT
		dataType: double
		lineageTag: d0c66411-b023-4884-a444-4e289ab9cfc3
		summarizeBy: sum
		sourceColumn: CURRENT_FACE_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'MV Home Amount'
		dataType: double
		lineageTag: c5ad5163-b0b0-4d6f-8e87-3022ce766c27
		summarizeBy: sum
		sourceColumn: MV Home Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MV_LOCAL_AMOUNT
		dataType: double
		lineageTag: c3ad9640-b99b-4b52-9b1b-fd5c7be36685
		summarizeBy: sum
		sourceColumn: MV_LOCAL_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Accrued
		dataType: double
		lineageTag: 69d95107-eac3-4aa5-a3e4-bcacd6a42631
		summarizeBy: sum
		sourceColumn: Accrued

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ACCRUED_LOCAL_AMOUNT
		dataType: double
		lineageTag: c7952398-2e67-416a-9490-e8db55ef63f5
		summarizeBy: sum
		sourceColumn: ACCRUED_LOCAL_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COST_BASIS_HOME_AMOUNT
		dataType: double
		lineageTag: f7b08633-e9f3-488c-a117-9eabe174c9b8
		summarizeBy: sum
		sourceColumn: COST_BASIS_HOME_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COST_BASIS_LOCAL_AMOUNT
		dataType: double
		lineageTag: e20dc918-c62d-4f1f-9afe-60fc2fa6f215
		summarizeBy: sum
		sourceColumn: COST_BASIS_LOCAL_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CURRENCY_CODE
		dataType: string
		lineageTag: c31f077a-37b5-4030-b2a8-0c19b1653913
		summarizeBy: none
		sourceColumn: CURRENCY_CODE

		annotation SummarizationSetBy = Automatic

	column PRICE_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: dd34dee4-2b9a-4ce6-bf98-b2c7e3cb57a5
		summarizeBy: none
		sourceColumn: PRICE_DATE

		variation Variation
			isDefault
			relationship: ed94ee12-ebfd-46ec-8bfa-b9d21d2b028d
			defaultHierarchy: LocalDateTable_3780016a-b842-4477-832e-afdc0cf06303.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Price Home Amount'
		dataType: double
		lineageTag: df471cb0-b772-4833-9877-d9e05e1b3483
		summarizeBy: sum
		sourceColumn: Price Home Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PRICE_LOCAL_AMOUNT
		dataType: double
		lineageTag: 61a60689-19f7-4538-90b1-22a12179e2f8
		summarizeBy: sum
		sourceColumn: PRICE_LOCAL_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PRICE_SOURCE_NAME
		dataType: string
		lineageTag: 3cda46c4-dcae-432f-8f09-055277a40f4a
		summarizeBy: none
		sourceColumn: PRICE_SOURCE_NAME

		annotation SummarizationSetBy = Automatic

	column 'FX Rate'
		dataType: double
		lineageTag: 69b62192-b45a-4e80-82f5-09ca5820c6db
		summarizeBy: sum
		sourceColumn: FX Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Portfolio Holding Percent'
		dataType: double
		lineageTag: 8a437667-f156-48fd-9c43-6180374efac8
		summarizeBy: sum
		sourceColumn: Portfolio Holding Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REDEMPTION_FACTOR
		dataType: double
		lineageTag: af517379-0705-483e-8b04-ee0490070dbe
		summarizeBy: sum
		sourceColumn: REDEMPTION_FACTOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BASE_MARKET_VALUE
		dataType: double
		lineageTag: 0ad19e3b-8e6c-4a20-98e6-bfa7945d034e
		summarizeBy: sum
		sourceColumn: BASE_MARKET_VALUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SOURCE_SYSTEM_STATUS_IDENTIFIER
		dataType: double
		lineageTag: 30ac0adf-9d1c-49bf-a537-0c652cd6c888
		summarizeBy: sum
		sourceColumn: SOURCE_SYSTEM_STATUS_IDENTIFIER

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ENDING_NAV_AMOUNT
		dataType: double
		lineageTag: a4c3e080-efb4-4550-a4f2-816d4cec9fd2
		summarizeBy: sum
		sourceColumn: ENDING_NAV_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BEGINNING_NAV_AMOUNT
		dataType: double
		lineageTag: 383c8825-dfc6-4a2a-be2a-f5ef8fef27ab
		summarizeBy: sum
		sourceColumn: BEGINNING_NAV_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SENTRY_PORTFOLIO_IDENTIFIER
		dataType: string
		lineageTag: 245372b3-c31e-4eb0-a2f6-af74679284de
		summarizeBy: none
		sourceColumn: SENTRY_PORTFOLIO_IDENTIFIER

		annotation SummarizationSetBy = Automatic

	column POSITION_SETTLED_QUANTITY
		dataType: double
		lineageTag: fbafd7c4-5c9f-4cbb-97db-f5afe3fd751d
		summarizeBy: sum
		sourceColumn: POSITION_SETTLED_QUANTITY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UNFUNDED_COMMITMENT_LOCAL
		dataType: double
		lineageTag: e85f8436-0b0d-45c9-a131-5404a1639134
		summarizeBy: sum
		sourceColumn: UNFUNDED_COMMITMENT_LOCAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DATA_PROVIDER_NAME
		dataType: string
		lineageTag: 5fcc26e3-4f87-4c87-ad9e-680935c0315e
		summarizeBy: none
		sourceColumn: DATA_PROVIDER_NAME

		annotation SummarizationSetBy = Automatic

	column VANTAGE_PORTFOLIO_IDENTIFIER
		dataType: string
		lineageTag: b462b417-9ff0-4d42-ba83-8608a3e3235b
		summarizeBy: none
		sourceColumn: VANTAGE_PORTFOLIO_IDENTIFIER

		annotation SummarizationSetBy = Automatic

	column VANTAGE_CUSTODIAN_ACCOUNT_IDENTIFIER
		dataType: string
		lineageTag: d29687f1-4fc9-4476-861d-a05780069dc4
		summarizeBy: none
		sourceColumn: VANTAGE_CUSTODIAN_ACCOUNT_IDENTIFIER

		annotation SummarizationSetBy = Automatic

	column CREATED_DATETIME
		dataType: dateTime
		formatString: General Date
		lineageTag: ec19f531-c678-4594-823a-cb12c4c81bf3
		summarizeBy: none
		sourceColumn: CREATED_DATETIME

		variation Variation
			isDefault
			relationship: 65c7ce15-a830-48f0-aa28-504812081a55
			defaultHierarchy: LocalDateTable_b5cf446a-8fb8-460d-9403-85e8deb36e0f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column CREATED_BY_NAME
		dataType: string
		lineageTag: 116060c1-a875-44c9-a4d2-59c689bd98c2
		summarizeBy: none
		sourceColumn: CREATED_BY_NAME

		annotation SummarizationSetBy = Automatic

	column CREATED_BY_COMMENTS
		dataType: string
		lineageTag: 24088a35-1761-4a14-87e6-6251a04eb7fe
		summarizeBy: none
		sourceColumn: CREATED_BY_COMMENTS

		annotation SummarizationSetBy = Automatic

	column MODIFIED_DATETIME
		dataType: dateTime
		formatString: General Date
		lineageTag: d85ee74c-c98f-4f26-a21c-fbf4f02a7c1e
		summarizeBy: none
		sourceColumn: MODIFIED_DATETIME

		variation Variation
			isDefault
			relationship: a9c4818c-ec79-48be-8172-9a78af2681de
			defaultHierarchy: LocalDateTable_3891e180-d5a0-4996-9d2a-d037b6ca9b58.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column MODIFIED_BY_NAME
		dataType: string
		lineageTag: 7d6baae6-283b-4504-8c4e-37c4d9b142b0
		summarizeBy: none
		sourceColumn: MODIFIED_BY_NAME

		annotation SummarizationSetBy = Automatic

	column MODIFIED_BY_COMMENTS
		dataType: string
		lineageTag: bf3cffed-1b14-4ef2-a5aa-9909f6dacf98
		summarizeBy: none
		sourceColumn: MODIFIED_BY_COMMENTS

		annotation SummarizationSetBy = Automatic

	column ID_DATE
		dataType: string
		lineageTag: 080348dc-ea32-429f-b943-3318f2c4fe07
		summarizeBy: none
		sourceColumn: ID_DATE

		annotation SummarizationSetBy = Automatic

	column ID_DATE_PORT
		dataType: string
		lineageTag: 80094c3e-4bb5-48de-95d2-e7becb7fb920
		summarizeBy: none
		sourceColumn: ID_DATE_PORT

		annotation SummarizationSetBy = Automatic

	partition HOLDING_2 = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(snowflake_url,"ANALYST_WH_XS"),
				    HUB_Database = Source{[Name="HUB",Kind="Database"]}[Data],
				    POSITION_Schema = HUB_Database{[Name="POSITION",Kind="Schema"]}[Data],
				    HOLDING_View = POSITION_Schema{[Name="HOLDING_DAILY",Kind="View"]}[Data],
				    #"Added Custom" = Table.AddColumn(HOLDING_View, "ID_DATE", each [INSTRUMENT_IDENTIFIER]&Date.ToText([PERIOD_END_DATE], [Format="yyyy-MM-dd"])),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom",{{"MV_HOME_AMOUNT", "MV Home Amount"}, {"PERIOD_END_DATE", "Period End Date"}, {"INSTRUMENT_IDENTIFIER", "Instrument Identifier"}, {"FX_RATE", "FX Rate"}, {"PORTFOLIO_HOLDING_PERCENT", "Portfolio Holding Percent"}, {"POSITION_QUANTITY", "Position Quantity"}, {"PRICE_HOME_AMOUNT", "Price Home Amount"}}),
				    #"Added Custom1" = Table.AddColumn(#"Renamed Columns", "ID_DATE_PORT", each [Instrument Identifier]&Date.ToText([Period End Date], [Format="yyyy-MM-dd"])&[PORTFOLIO_IDENTIFIER]),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom1",{{"ACCRUED_HOME_AMOUNT", "Accrued"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

